name: terraform-security-compliance
on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      tflint_version:
        required: false
        type: string
    secrets:
      tf_cloud_token:
        required: true
jobs:
  # tfsec:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: setup terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_version: ${{ inputs.terraform_version }}
  #         cli_config_credentials_token: ${{ secrets.tf_cloud_token }}
  #     - name: terraform init
  #       run: terraform init -backend=false
  #     - name: give temporary permissions
  #       run: sudo chown -R root:root $GITHUB_WORKSPACE
  #     - name: tfsec
  #       uses: reviewdog/action-tfsec@v1.15.0
  #       with:
  #         github_token: ${{ secrets.github_token }}
  #         fail_on_error: true
  #         filter_mode: file
  #         tfsec_flags: "--exclude-downloaded-modules"
  #         level: warning
  checkov:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
          cli_config_credentials_token: ${{ secrets.tf_cloud_token }}
      - name: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
