name: terraform-apply
on:
  push:
    branches: [main]
jobs:
  sandbox:
    if: ${{ !contains(github.event.head_commit.message , 'hotfix') }}
    name: sandbox
    uses: ./.github/workflows/apply.yaml
    with:
      terraform_version: "1.1.9"
      tf_workspace: "terraform-pipeline-poc-sandbox-us-west-2"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
  qa:
    if: ${{ !contains(github.event.head_commit.message , 'hotfix') }}
    name: qa
    needs: sandbox
    uses: ./.github/workflows/apply.yaml
    with:
      terraform_version: "1.1.9"
      tf_workspace: "terraform-pipeline-poc-qa-us-west-2"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
  dev:
    if: ${{ !contains(github.event.head_commit.message , 'hotfix') }}
    name: dev
    needs: qa
    uses: ./.github/workflows/apply.yaml
    with:
      terraform_version: "1.1.9"
      tf_workspace: "terraform-pipeline-poc-dev-us-west-2"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
  prod:
    name: prod
    needs: dev
    uses: ./.github/workflows/apply.yaml
    with:
      terraform_version: "1.1.9"
      tf_workspace: "terraform-pipeline-poc-prod-us-west-2"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
  hotfix-prod:
    if: ${{ contains(github.event.head_commit.message , 'hotfix') }}
    name: hotfix-prod
    uses: ./.github/workflows/apply.yaml
    with:
      terraform_version: "1.1.9"
      tf_workspace: "terraform-pipeline-poc-prod-us-west-2"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
