name: terraform-plan
on:
  pull_request:
    branches: [main]
env:
  TERRAFORM_VERSION: "1.1.9"

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml@37340ac349236feac472c07aa24cacab26eab17b
    with:
      terraform_version: ${{ env.TERRAFORM_VERSION }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
