name: terraform-plan
on:
  pull_request:
    branches: [main]
env:
  TERRAFORM_VERSION: "1.1.9"

jobs:
  validate:
    uses: .github/workflows/reusable/validate.yaml
    with:
      terraform_version: ${{ env.TERRAFORM_VERSION }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
