name: terraform-apply
on:
  push:
    branches: [main]
env:
  TERRAFORM_VERSION: "1.1.9"
jobs:
  test:
    name: test behavior
    runs-on: ubuntu-20.04
    steps:
      - name: test commit
        run: echo ${{ contains(github.event.head_commit.message , 'hotfix') }}
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
  apply-sandbox:
    if: false == ${{ contains(github.event.commits.*.message , 'hotfix') }}
    name: "apply-sandbox"
    runs-on: ubuntu-20.04
    env:
      TF_WORKSPACE: "terraform-pipeline-poc-sandbox-us-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        id: init
        run: TF_LOG=info terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply
        continue-on-error: true
  apply-qa:
    if: false == ${{ contains(github.event.commits.*.message , 'hotfix') }}
    needs: "apply-sandbox"
    name: "apply-qa"
    runs-on: ubuntu-20.04
    env:
      TF_WORKSPACE: "terraform-pipeline-poc-qa-us-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        id: init
        run: TF_LOG=info terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply
  apply-dev:
    if: false == ${{ contains(github.event.commits.*.message , 'hotfix') }}
    needs: "apply-qa"
    name: "apply-dev"
    runs-on: ubuntu-20.04
    env:
      TF_WORKSPACE: "terraform-pipeline-poc-dev-us-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        id: init
        run: TF_LOG=info terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply
  apply-prod:
    if: false == ${{ contains(github.event.commits.*.message , 'hotfix') }}
    needs: "apply-dev"
    name: "apply-prod"
    runs-on: ubuntu-20.04
    env:
      TF_WORKSPACE: "terraform-pipeline-poc-prod-us-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        id: init
        run: TF_LOG=info terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply
  ## TODO: Implement Conditional to avoid repeating code
  apply-prod-hotfix:
    if: ${{ contains(github.event.commits.*.message , 'hotfix') }}
    name: "apply-prod-hotfix"
    runs-on: ubuntu-20.04
    env:
      TF_WORKSPACE: "terraform-pipeline-poc-prod-us-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        id: init
        run: TF_LOG=info terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply
