name: terraform-plan
on:
  pull_request:
    branches: [main]
env:
  TERRAFORM_VERSION: "1.1.9"

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
    with:
      terraform_version: "1.1.9"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
  security-compliance:
    uses: ./.github/workflows/security-compliance.yaml
    with:
      terraform_version: "1.1.9"
    secrets:
      tf_cloud_token: ${{ secrets.TF_CLOUD_TOKEN }}
